name: spark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]

jobs:
  spark:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4  # Checkout repository

    - run: ls -la  # List files to confirm dataset.csv is present

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.5.3'
        hadoop-version: '3'

    - run: mkdir -p results  # Ensure results directory exists

    - run: spark-submit --master local data.py  # Run your Spark job
    
    - run: ls -la results  # Check output

    - name: GIT commit and push results
      env: 
        CI_COMMIT_MESSAGE: "Save Spark results"
        CI_COMMIT_AUTHOR: "adsoft"
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "adsoft@live.com.mx"
        git add results
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
