name: spark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types: [spark]

jobs:
  spark:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Files (Debugging)
      run: ls -la  

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin

    - name: Set up Apache Spark
      uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.5.3'
        hadoop-version: '3'

    - name: Download Dataset
      run: wget -O Ecommerce_Consumer_Behavior_Analysis_Data.csv https://raw.githubusercontent.com/YOUR_USERNAME/YOUR_REPO/main/datasets/Ecommerce_Consumer_Behavior_Analysis_Data.csv

    - name: Verify Dataset
      run: ls -la && head -n 5 Ecommerce_Consumer_Behavior_Analysis_Data.csv

    - name: Run Spark Job
      run: spark-submit --master local people.py 

    - name: Commit and Push Spark Results
      env: 
        CI_COMMIT_MESSAGE: save spark results
        CI_COMMIT_AUTHOR: adsoft 
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "adsoft@live.com.mx"
        git add results
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
